.TH .EXPORT_CHUNK 1 2023-Aug "" ".export_chunk"
.SH NAME
.export_chunk \- .export_chunk(wav, chunk.name)
.SH SYNOPSIS
\fI.export_chunk(wav, chunk.name)\fR
.SH OPTIONS
.PP
\fBwav\fB \fR\- . 
.PP
.PP
\fBchunk.name\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function..export_chunk at chunks.R:line 22
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
