.TH EXPORT_FROM_CHUNKS 1 2024-Nov "" "make batch export of the images on the disk"
.SH NAME
export_from_chunks \- export_from_chunks(wavFile, output.dir)
.SH SYNOPSIS
\fIexport_from_chunks(wavFile, output.dir)\fR
.SH OPTIONS
.PP
\fBwavFile\fB \fR\- . the file path to the disk image in wave file
.PP
.PP
\fBoutput.dir\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.export_from_chunks at chunks.R:line 14
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2024
