.TH EXPORT_FROM_CHUNKS 1 2023-Aug "" "export_from_chunks"
.SH NAME
export_from_chunks \- export_from_chunks(wavFile, output.dir)
.SH SYNOPSIS
\fIexport_from_chunks(wavFile, output.dir)\fR
.SH OPTIONS
.PP
\fBwavFile\fB \fR\- . 
.PP
.PP
\fBoutput.dir\fB \fR\- . 
.PP
.SH FILES
.PP
SMRUCC/R#.declare_function.export_from_chunks at chunks.R:line 8
.PP
.SH COPYRIGHT
Copyright © xieguigang, MIT Licensed 2023
