.\" man page create by R# package system.
.TH GOLDENRECORD 1 2000-Jan "chunk_size" "chunk_size"
.SH NAME
chunk_size \- measure the data chunk size of the wav data for current image chunk
.SH SYNOPSIS
\fIchunk_size(\fBwav\fR as <generic> WaveFile, 
\fBchunk\fR as <generic> ImageChunk);\fR
.SH DESCRIPTION
.PP
measure the data chunk size of the wav data for current image chunk
.PP
.SH OPTIONS
.PP
\fBwav\fB \fR\- -. 
.PP
.PP
\fBchunk\fB \fR\- -. 
.PP
.SH SEE ALSO
goldenRecord
.SH FILES
.PP
voyager-1.dll
.PP
