.\" man page create by R# package system.
.TH GOLDENRECORD 1 2000-Jan "decode" "decode"
.SH NAME
decode \- Decode the wav data as the pixel scans
.SH SYNOPSIS
\fIdecode(\fBwav\fR as <generic> WaveFile, 
\fBchunk\fR as <generic> ImageChunk, 
\fBdecode\fR as <generic> DecoderArgument, 
\fBsize\fR as integer = 364, 
\fBoffsetLeft\fR as double = 0.2, 
\fBoffsetRight\fR as double = 0.2, 
[\fB<Environment>\fR]);\fR
.SH DESCRIPTION
.PP
Decode the wav data as the pixel scans
.PP
.SH OPTIONS
.PP
\fBwav\fB \fR\- -. 
.PP
.PP
\fBchunk\fB \fR\- -. 
.PP
.PP
\fBdecode\fB \fR\- -. 
.PP
.PP
\fBsize\fB \fR\- -. 
.PP
.PP
\fBenv\fB \fR\- -. 
.PP
.SH SEE ALSO
goldenRecord
.SH FILES
.PP
voyager-1.dll
.PP
